### ISSUE TITLE
This not work 

### ISSUE THREAD

**Issue by hichay** [DefCon42/ironbrew-2#3]
It build fine but cant start the lua file to run it in Fivem

**Comment by DefCon42** [comment]
I need more information. What doesn't work? Does the Lua file error? What errors, if anything? Is there a syntactic problem?

**Comment by hichay** [comment]
Do you have any thing to contact. i can make some screen about it

**Comment by hichay** [comment]
`[    792484] [    GTAProcess]             MainThrd/ 	@esx_advancedweapons/client/client.lua:20: in function <@esx_advancedweapons/client/client.lua:20>
[    792500] [    GTAProcess]             MainThrd/ 	(...tail calls...)
[    792531] [    GTAProcess]             MainThrd/ Failed to load script client/client.lua.
[    792578] [    GTAProcess]             MainThrd/ ^1SCRIPT ERROR: @esx_advancedweapons/client/client.lua:20: attempt to call a nil value (upvalue 'c')^7`
this is error when i try to use the lua file

**Comment by hichay** [comment]
need help to make it work for fivem

**Comment by DefCon42** [comment]
Contact me on Discord: DefCon42#1194

**Comment by hichay** [comment]
Added. pls accept
